# Generated by Django 3.0.7 on 2020-06-17 08:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_aggiunta_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Guanti', 'Guanti'), ('Giacca', 'Giacca'), ('Pantaloni', 'Pantaloni'), ('Tuta', 'Tuta'), ('Stivali', 'Stivali'), ('Casco', 'Casco'), ('Manutenzione moto', 'Manutenzione moto')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
