# Generated by Django 3.0.7 on 2020-06-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_aggiunta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Guanti', 'Guanti'), ('Giacca', 'Giacca'), ('Pantaloni', 'Pantaloni'), ('Tuta', 'Tuta'), ('Stivali', 'Stivali'), ('Casco', 'Casco'), ('Manutenzione moto', 'Manutenzione moto')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
