# Generated by Django 3.0.7 on 2020-06-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_aggiunta_taglia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
